In [ ]:
import numpy as np

In [ ]:
escalar = 5.67989
vector = np.array([1,2,3])
matriz=np.array([[1,2,3],[3,3,4]])
tensor= np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],

])
print(escalar)
print(vector)
print(matriz)
print(tensor)

5.67989
[1 2 3]
[[1 2 3]
 [3 3 4]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
print(vector.shape)
print(matriz.shape)
print(tensor.shape)

(3,)
(2, 3)
(3, 3, 3)


- Al intentar **escalar_t=escalar.T** nos devolvera AttributeError: 'float' object has no attribute 'T'

In [ ]:
vector_t = vector.T
print(vector_t)

[1 2 3]


In [ ]:
matriz_t = matriz.T
print(matriz)
print(matriz.shape)
print(matriz_t)
print(matriz_t.shape)


[[1 2 3]
 [3 3 4]]
(2, 3)
[[1 3]
 [2 3]
 [3 4]]
(3, 2)


In [ ]:
tensor_t=tensor.T
print(tensor)
print(tensor.shape)
print(tensor_t)
print(tensor.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
(3, 3, 3)
[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]
(3, 3, 3)


# Suma de Matrices



In [ ]:
 matriz_a=np.array([[1,2,3],[1,5,6],[3,3,4]])
 matriz_b=np.array([[1,2,3],[1,6,7],[3,3,4]])
 
 A = matriz_a
 B = matriz_b
 C = A+B
 print(A)
 print(B)
 print(C)

[[1 2 3]
 [1 5 6]
 [3 3 4]]
[[1 2 3]
 [1 6 7]
 [3 3 4]]
[[ 2  4  6]
 [ 2 11 13]
 [ 6  6  8]]


In [ ]:
D = matriz + escalar
print(D)

[[6.67989 7.67989 8.67989]
 [8.67989 8.67989 9.67989]]


# Reto Platzi   

In [ ]:
mat_reto=np.random.randint(10,size=(5,5))
print(mat_reto)
print(mat_reto.T)

suma_mat= mat_reto+mat_reto.T
print(suma_mat)

[[3 9 0 0 1]
 [7 7 1 2 8]
 [4 2 9 0 5]
 [4 4 9 3 8]
 [2 0 3 4 1]]
[[3 7 4 4 2]
 [9 7 2 4 0]
 [0 1 9 9 3]
 [0 2 0 3 4]
 [1 8 5 8 1]]
[[ 6 16  4  4  3]
 [16 14  3  6  8]
 [ 4  3 18  9  8]
 [ 4  6  9  6 12]
 [ 3  8  8 12  2]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=574e9a1c-d8dd-4ee0-b56a-658b2637ff93' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>